


def line_ups():
    gk = 1
    name = "Ter Stegen"
    print(" ------------------------------------------------------------------------------ ")
    print("|                               |            |                                 |")
    print("|                               |            |                                 |")   
    print("|                                ------------                                  |")
    print(f"|                                  {gk}                                         |")   
    print(f"|                                 {name}                                        |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")   
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")   
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")   
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")   
    print("|                                                                              |")
    print(" ------------------------------------------------------------------------------ ")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")   
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")   
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")   
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")   
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                                                              |")
    print("|                                ------------                                  |")
    print("|                               |            |                                 |")   
    print("|                               |            |                                 |")
    print(" ------------------------------------------------------------------------------ ")


line_ups()

